name: Create Jira Issue on Label

on:
  issues:
    types:
      - labeled

jobs:
  create-jira-issue:
    if: contains(github.event.label.name, 'bug') # Trigger only when the 'bug' label is added
    runs-on: ubuntu-latest
    steps:
      - name: Login to Jira
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }} # The base URL of your Jira instance
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }} # The email associated with your Jira user
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }} # The API token for Jira

      - name: Create Jira Issue
        uses: atlassian/gajira-create@v3
        with:
          project: JGI # The Jira project key where the issue should be created
          issuetype: Bug # The type of issue to create
          summary: ${{ github.event.issue.title }} # The title of the issue from GitHub
          description: |
            **Reporter:** ${{ github.actor }}
            
            **Issue URL:** ${{ github.event.issue.html_url }}
            
            **Description:** ${{ github.event.issue.body }}